import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import "bootstrap/dist/css/bootstrap.min.css";
import Navbars from "./components/Navbar/Navbars";
import NavbarTop from "./components/Navbar/NavbarTop";
import Footer from "./components/Footer/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NavbarTop />
        <Navbars />
        {children}
        <Footer />
      </body>
    </html>
  );
}
